--MY SQL

CREATE TABLE ALUNOS
( ID INT(2),
  NOME VARCHAR(50),
  VALOR INT(3)
);

INSERT INTO ALUNOS(ID,NOME,VALOR) VALUES(1,'JULIA',88);
INSERT INTO ALUNOS(ID,NOME,VALOR) VALUES(2,'CAROL',68);
INSERT INTO ALUNOS(ID,NOME,VALOR) VALUES(3,'MARIA',99);
INSERT INTO ALUNOS(ID,NOME,VALOR) VALUES(4,'ANDREIA',78);
INSERT INTO ALUNOS(ID,NOME,VALOR) VALUES(5,'JAQUELINE',63);
INSERT INTO ALUNOS(ID,NOME,VALOR) VALUES(6,'MARCELA',81);


SELECT result.* FROM (
	(SELECT NOME, TRUNCATE((VALOR/10),0)+1 AS NOTA, VALOR FROM ALUNOS WHERE VALOR > 69)
	UNION (SELECT NULL AS NOME, TRUNCATE((VALOR/10),0)+1 AS NOTA, VALOR FROM ALUNOS WHERE VALOR < 69)
)result ORDER BY result.NOTA DESC,result.NOME DESC,VALOR ASC;
