/*MY SQL*/

/*CREATE THE TABLES*/
CREATE TABLE DOGS(
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

CREATE TABLE CATS(
	ID INTEGER NOT NULL PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL
);

/*POPULATE THE TABLES*/
INSERT INTO CATS(ID,NAME) VALUES (1,'SNOP');

INSERT INTO CATS(ID,NAME) VALUES (2,'DONNA');

INSERT INTO CATS(ID,NAME) VALUES (3,'SUN');

INSERT INTO CATS(ID,NAME) VALUES (4,'MOON');

INSERT INTO CATS(ID,NAME) VALUES (5,'MEL');



INSERT INTO DOGS(ID,NAME) VALUES (1,'BOB');

INSERT INTO DOGS(ID,NAME) VALUES (2,'SNOOP');

INSERT INTO DOGS(ID,NAME) VALUES (3,'BRUTUS');

INSERT INTO DOGS(ID,NAME) VALUES (4,'MOON');

INSERT INTO DOGS(ID,NAME) VALUES (5,'SAM');

INSERT INTO DOGS(ID,NAME) VALUES (6,'MEL');

/* EXECUTE THE QUERY */
SELECT DISTINCT(animal.NAME) FROM 
(
	(SELECT NAME FROM DOGS) UNION
	(SELECT NAME FROM CATS)
	
)animal;