/* Department Highest Salary 
https://leetcode.com/problems/department-highest-salary/
*/
CREATE TABLE EMPLOYEE_2(
	ID INT,
	NAME VARCHAR(50),
	SALARY INT,
	DEPARTMENTID INT
);


INSERT INTO EMPLOYEE_2(ID, NAME, SALARY, DEPARTMENTID) VALUES (1,'JOE',70000,1);
INSERT INTO EMPLOYEE_2(ID, NAME, SALARY, DEPARTMENTID) VALUES (2,'JIM',90000,1);
INSERT INTO EMPLOYEE_2(ID, NAME, SALARY, DEPARTMENTID) VALUES (3,'HENRY',80000,2);
INSERT INTO EMPLOYEE_2(ID, NAME, SALARY, DEPARTMENTID) VALUES (4,'SAM',60000,2);
INSERT INTO EMPLOYEE_2(ID, NAME, SALARY, DEPARTMENTID) VALUES (5,'MAX',90000,1);

CREATE TABLE DEPARTMENT(
	ID INT, 
	NAME VARCHAR(20)
);

INSERT INTO DEPARTMENT(ID, NAME) VALUES (1,'IT')
INSERT INTO DEPARTMENT(ID, NAME) VALUES (2,'SALES')

/* Solution */
SELECT d.NAME Department , e.NAME Employee , e.SALARY Salary 
FROM (SELECT MAX(s.SALARY) HIGHEST_SAL, s.DEPARTMENTID
FROM EMPLOYEE s
GROUP BY s.DEPARTMENTID) high_sal_per_dept 
INNER JOIN EMPLOYEE e ON e.SALARY = high_sal_per_dept.HIGHEST_SAL AND e.DEPARTMENTID = high_sal_per_dept.DEPARTMENTID
INNER JOIN DEPARTMENT d ON d.ID = e.DEPARTMENTID;