/*Exchange Seats
https://leetcode.com/problems/exchange-seats/
*/
CREATE TABLE SEAT(
	ID INT,
	STUDENT VARCHAR(60)
);

INSERT INTO SEAT(ID, STUDENT) VALUES (1,'ABBOT');
INSERT INTO SEAT(ID, STUDENT) VALUES (2,'DORIS');
INSERT INTO SEAT(ID, STUDENT) VALUES (3,'EMERSON');
INSERT INTO SEAT(ID, STUDENT) VALUES (4,'GREEN');
INSERT INTO SEAT(ID, STUDENT) VALUES (5,'JEAMES');


SELECT result.id, CASE 
WHEN (result.NEXT_STUDENT IS NOT NULL AND MOD(result.ID,2) = 1) THEN result.NEXT_STUDENT
WHEN (result.PREVIOUS_STUDENT IS NOT NULL AND MOD(result.ID,2) = 0) THEN result.PREVIOUS_STUDENT
ELSE result.STUDENT END AS "STUDENT"
FROM 
(SELECT seat.*, LAG(seat.STUDENT) OVER (ORDER BY seat.ID) PREVIOUS_STUDENT, LEAD(seat.STUDENT) OVER(ORDER BY seat.ID) NEXT_STUDENT

FROM SEAT seat) result
